version: "3.8"
services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./app:/usr/src/app/app
    environment:
      - PYTHONUNBUFFERED=1

