stages:
  preprocess:
    cmd: python -m pipelines.preprocess
    deps:
      - data/raw/arxiv100.csv
      - data_processing/versioning.py
    outs:
      - data/processed/v1
      - data/processed/v2
      - data/processed/v3
    metrics:
      - data/metrics/processing_metrics.json

  train:
    cmd: python -m pipelines.train --data_version v1 --run_experiments
    deps:
      - data/processed/v1
      - model/bert_trainer.py
      - pipelines/train.py
    metrics:
      - models/metrics/train_metrics.json

  fine_tune:
    cmd: python -m pipelines.fine_tune --data_version v2
    deps:
      - data/processed/v2
      - model/bert_trainer.py
      - pipelines/fine_tune.py
    metrics:
      - models/metrics/fine_tune_metrics.json
      
  check_feedback:
    cmd: python -m pipelines.fine_tune --check_feedback
    deps:
      - data/feedback/user_corrections.csv
      - model/bert_trainer.py
      - pipelines/fine_tune.py
    metrics:
      - models/metrics/feedback_fine_tune_metrics.json
    always_changed: true


