{
 "title": "mlops_app",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(classify_pdf_requests_total) by (status)",
     "legendFormat": "classify_pdf"
    },
    {
     "expr": "sum(feedback_requests_total) by (status)",
     "legendFormat": "feedback"
    },
    {
     "expr": "sum(samples_requests_total) by (status)",
     "legendFormat": "samples"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(classify_pdf_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "classify_pdf"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(feedback_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "feedback"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(samples_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "samples"
    }
   ]
  },
  {
   "title": "Unique App Users by IP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (ip) (unique_users_total))",
     "legendFormat": "user_ip"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_cpu_seconds_total{mode=~\"system|user\"}[1m]))",
     "legendFormat": "{{cpu}}"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"system|user\"}[1m]))",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Installed" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "Swapped"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}