global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']